### ISSUE TITLE
Bikin dokumentasinya bang.

### ISSUE THREAD

**Issue by yukebrillianth** [fathalfath30/license-manager#1]
berarti kalau pake ini kita bisa bikin lisensi untuk aplikasi kita?

**Comment by fathalfath30** [comment]
Sebelumnya repo ini jauh dari kata selesai bang karena kebetulan lagi padat juga kerjaan di kantor dan udah saya note di readme.md. 

`FYI : This library is still under heavy development and is not in a completed state! You will be able to do nothing with it right now.`

kalau misalnya saya udah mulai aktif lagi disini, dokumentasinya pasti dibuat kok. Goalsnya itu kita bisa kasih license ke aplikasi kita jadi engga sembarang bisa di jalankan (kecuali kalau otak-atik source code atau vendor).

Best regard's
Alfath
